api/urls.py
from rest_framework.routers import SimpleRouter

from . import views

router = SimpleRouter()
router.register('adverts', views.AdvertViewSet, basename='adverts')
router.register('', views.AdvertViewSet, basename='adverts')

urlpatterns = router.urls

job/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('mining/', include('mining.urls', namespace='mining')),
]

mining/urls.py
from django.urls import path

from . import views

app_name = 'mining'

urlpatterns = [
    path('', views.AdvertListView.as_view(), name='advert_list'),
    path('<slug:advert>/', views.advert_detail, name='advert_detail'),
]

api/models.py
from django.db import models

# Create your models here.

inquire/models.py
from django.db import models

# Create your models here.

mining/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class ActiveManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=True)


class Advert(models.Model):
    organization = models.CharField(max_length=60)
    post = models.CharField(max_length=60)
    slug = models.SlugField(max_length=120, unique='pk', default='')
    text = models.TextField()
    salary = models.TextField(max_length=60, null=True)
    person = models.CharField(max_length=60)
    phone = models.CharField(max_length=60)
    pub_date = models.DateField(blank=True, null=True)
    status = models.BooleanField(default=True)

    objects = models.Manager()  # Stanart manager
    active = ActiveManager()  # New manager

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return f'{self.organization} {self.post}'

    def get_absolute_url(self):
        return reverse('mining:advert_detail', args=[self.slug, ])


class Activity(models.Model):
    advert = models.ForeignKey(Advert, on_delete=models.CASCADE, related_name='actions')
    timestamp = models.DateTimeField(default=timezone.now)  # auto_now_add=True, 
    action = models.TextField()

    class Meta:
        verbose_name_plural = 'Activties'

    def __str__(self):
        return f"{self.timestamp.strftime('%d.%m %H:%M')} {self.action}"

mining/forms.py
from django import forms

from .models import Activity


class ActionForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ('action',)

api/views.py
from rest_framework import viewsets

from api.serializers import AdvertSerializer
from mining.models import Advert


class AdvertViewSet(viewsets.ModelViewSet):
    queryset = Advert.active.all()
    serializer_class = AdvertSerializer
    lookup_field = 'slug'

inquire/views.py
from django.shortcuts import render

# Create your views here.

mining/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from mining.models import Advert
from .forms import ActionForm


class AdvertListView(ListView):
    queryset = Advert.active.all()
    ordering = ('-pk')
    context_object_name = 'adverts'
    template_name = "mining/adverts/list.html"


class AdvertDetailView(DetailView):  # Допустим, так
    pass


def advert_detail(request, advert):
    advert = get_object_or_404(Advert, slug=advert)
    # List of actions for this advert
    actions = advert.actions.all()

    new_action = None

    if request.method == 'POST':
        # A new action was posted
        action_form = ActionForm(data=request.POST)
        if action_form.is_valid():
            # Create action object, but don't save to database yet.
            new_action = action_form.save(commit=False)
            # Assign the current advert to the action
            new_action.advert = advert
            # save the action to database
            new_action.save()
    else:
        action_form = ActionForm()
    return render(request, "mining/adverts/detail.html",
                  {'advert': advert,
                   'actions': actions,
                   'new_action': new_action,
                   'action_form': action_form})

mining/templates/mining/adverts/detail.html
{% load static %}
{% load mining_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <title>Advert detail</title>
</head>
<body>
<div id="content">
    <h1>{{ advert.organization }}</h1>
    <p>
    <h2>{{ advert.post }}</h2></p>
    <p>{{ advert.text|markdown }}</p>
    <p><u>Обещанный оклад:</u> {{ advert.salary }}</p>
    <p class="date"><i>Опубликовано: {{ advert.pub_date }}</i></p>
    <u>Действия:</u>
    {% for action in actions %}
        <div class="comment">
            <p class="info">{{ action }}</p>
        </div>
    {% empty %}
        <p>Не было активности</p>
    {% endfor %}
    {% if new_action %}
        <h3>Действие добавлено.</h3>
        <p>
            <a href="{% url 'mining:advert_list' %}">К списку задач</a>
        </p>
    {% else %}
        <b>Новое действие:</b>
        <form method="post">
            {{ action_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Добавить"></p>
        </form>
        <br>
        <p>
            <a href="{% url 'mining:advert_list' %}">К списку задач</a>
        </p>
    {% endif %}


</div>

</body>
</html>

mining/templates/mining/adverts/list.html
{% load static %}
{% load mining_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <title>Adverts</title>
</head>
<body>
<h1>Активные объявления</h1>
{% for advert in adverts %}
    <p><a href="{{ advert.get_absolute_url }}"> <b>{{ advert.organization }}</b> {{ advert.post }}</a></p>
{% endfor %}
</body>
</html>